services:
  backend:
    image: proj:p3_dl_lambda
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=mlops-proj-predict
      - TEST_RUN=False
      - AWS_DEFAULT_REGION=us-east-2
      - RUN_ID=7fffc2ed5cbc451890a7ad1e23d20162
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
