channels:
- conda-forge
dependencies:
- python=3.8.12
- pip<=22.2
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - dataclasses==0.6
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - typing-extensions==4.2.0
name: mlflow-env
