datasets:
  wine:
    column_mapping:
      numerical_features:
        - 'alcohol'
        - 'volatile acidity'
        - 'sulphates'
    data_format:
      header: true
      separator: ';'
    monitors:
      - data_drift
    reference_file: ./datasets/winequality-white.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
